### ISSUE TITLE
Link for "Edit this document on GitHub" is broken

### ISSUE THREAD

**Issue by beatak** [rubygems/bundler-site#930] opened 2022-09-17 00:46 UTC
The link on the footer "`Edit this document on GitHub`" is linking to `https://github.com/rubygems/bundler-site/blob/master/source/man/*.html.erb`. It seems the source of truth has moved to `https://github.com/rubygems/rubygems/tree/master/bundler/lib/bundler/man/*`.

**Comment by deivid-rodriguez** [comment] 2022-09-17 08:38
Thanks for reporting this, I assume you were already planning on fixing https://github.com/rubygems/rubygems/issues/5932 :)

@tnir Any ideas? I think we actually fixed this not a long time ago, I guess it broken again with the recent structure normalizations?

**Comment by tnir** [comment] 2022-09-18 03:22
@beatak Thanks for reporting.

In #615, I addressed this only in https://bundler.io/v2.3/man/bundle-exec.1.html, not in https://bundler.io/man/bundle-exec.1.html as described implicitly in https://github.com/rubygems/bundler-site/issues/620#issuecomment-1174110210.

@deivid-rodriguez I would like to address this root cause in a way described in #618.

**Comment by deivid-rodriguez** [comment] 2022-12-15 18:07
Fixed by #965!

**Comment by tnir** [comment] 2022-12-30 06:03
These links no longer exist since the top-level pages do not exist in #993.

**Closed by tnir** 2022-12-30 06:03 UTC
