### ISSUE TITLE
Getting started documentation does not explain how to install bundler

### ISSUE THREAD

**Issue by fulldecent** [rubygems/bundler-site#909] opened 2022-09-02 14:24 UTC
The getting started documentation at https://bundler.io/guides/getting_started.html is the first step of the documentation https://bundler.io/docs.html.

This first step should explain how to install bundler.

For example I just installed ruby on macOS:

```sh
brew install ruby
```

And now I would like to use bundler. I tried:

```sh
bundle
```

which produced:

> /Users/XXXX/.gem/ruby/3.1.0/bin/bundle:25:in \`load\': cannot load such file -- /opt/homebrew/lib/ruby/gems/3.1.0/gems/bundler-2.1.4/exe/bundle (LoadError)
        from /Users/XXXX/.gem/ruby/3.1.0/bin/bundle:25:in \`\<main\>\'

This issue is NOT CONCERNED WITH FIXING MY PROBLEM. I don't care about that problem right now. This is issue is concerned that the documentation's first step does not bring an interested potential customer from not using bundler to using bundler.

**Comment by tnir** [comment] 2022-09-05 02:05
@fulldecent Thanks for your feedback. Unfortunately they cannot reproduce your environment only with what you showed above. You ran `/Users/XXXX/.gem/ruby/3.1.0/bin/bundle`, which is what you installed besides Homebrew, instead of `/opt/homebrew/opt/ruby/bin/bundle`, which was installed by Homebrew.

First you should confirm which executable you are running like the following commands:
```sh
$ which bundle
/opt/homebrew/opt/ruby/bin/bundle
$ which ruby
/opt/homebrew/opt/ruby/bin/ruby
```

And you can check the version of Ruby and Bundler you are using like:
```sh
$ ruby --version
ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [arm64-darwin21]
$ bundle --version
Bundler version 2.3.11
```

As the error log you got showed, you are using Bundler 2.1.4. Closing but I hope you comment additional information about the situation you ran into in this issue 🍀

**Closed by tnir** 2022-09-05 02:05 UTC

**Comment by fulldecent** [comment] 2022-09-07 03:50
Got it, thank you. It appears I do not have Ruby properly installed. That is its own war and I suppose it is bundle is supposed to come with Ruby and the two should work together.
